import { Stakeholder, Contact, Engagement, Opportunity, FollowUp } from './supabase';

export const seedStakeholders: Stakeholder[] = [
  {
    id: '1',
    name: 'Gates Foundation',
    category: 'Foundation',
    organization_type: 'Philanthropic Foundation',
    country: 'United States',
    county: null,
    website: 'https://www.gatesfoundation.org',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Strategic Priority',
    program_areas: ['Women Empowerment', 'Youth Development', 'Digital Skills'],
    areas_of_interest: ['Health', 'Education', 'Agriculture'],
    strategic_alignment: 'High — core mission alignment on education and health programs',
    notes: 'Key strategic partner. Annual RFP released in Q1. Strong interest in youth programs.',
    tags: ['Tier 1', 'High Priority', 'Education'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2024-01-15T09:00:00Z',
    updated_at: '2026-05-20T14:30:00Z',
  },
  {
    id: '2',
    name: 'Mastercard Foundation',
    category: 'Foundation',
    organization_type: 'Philanthropic Foundation',
    country: 'Canada',
    county: null,
    website: 'https://mastercardfdn.org',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Strategic Priority',
    program_areas: ['Youth Development', 'Entrepreneurship'],
    areas_of_interest: ['Youth Employment', 'Financial Inclusion', 'Education'],
    strategic_alignment: 'High — Scholars Program aligns with our youth development mandate',
    notes: 'Active partnership through Scholars Program. Renewal discussion in September.',
    tags: ['Tier 1', 'Active Partner', 'Youth'],
    assigned_officer: 'James Otieno',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2026-05-15T11:20:00Z',
  },
  {
    id: '3',
    name: 'Safaricom PLC',
    category: 'Corporate',
    organization_type: 'Telecommunications',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://www.safaricom.co.ke',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Growth Opportunity',
    program_areas: ['Digital Skills', 'Youth Development'],
    areas_of_interest: ['Digital Innovation', 'CSR', 'Youth Empowerment'],
    strategic_alignment: 'Medium — CSR programs align with our digital literacy initiatives',
    notes: 'Safaricom Foundation is separate entity. Key contact is the Partnerships Lead.',
    tags: ['Corporate', 'CSR', 'Digital'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2024-03-05T08:00:00Z',
    updated_at: '2026-04-10T16:45:00Z',
  },
  {
    id: '4',
    name: 'US Embassy Nairobi',
    category: 'Embassy',
    organization_type: 'Diplomatic Mission',
    country: 'United States',
    county: 'Nairobi',
    website: 'https://ke.usembassy.gov',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Strategic Priority',
    program_areas: ['Women Empowerment', 'Youth Development', 'Climate Action'],
    areas_of_interest: ['Democracy', 'Youth', 'Women Empowerment', 'Environment'],
    strategic_alignment: 'High — PEPFAR and USAID programs match our mandate',
    notes: 'Small Grants Program deadline usually in March. Ambassador Fund for Cultural Preservation.',
    tags: ['Embassy', 'Grants', 'High Priority'],
    assigned_officer: 'James Otieno',
    created_at: '2024-01-20T07:30:00Z',
    updated_at: '2026-03-15T09:15:00Z',
  },
  {
    id: '5',
    name: 'Ford Foundation',
    category: 'Foundation',
    organization_type: 'Philanthropic Foundation',
    country: 'United States',
    county: null,
    website: 'https://www.fordfoundation.org',
    linkedin: null,
    twitter: null,
    status: 'Prospect',
    partner_priority: 'Growth Opportunity',
    program_areas: ['Women Empowerment'],
    areas_of_interest: ['Inequality', 'Democracy', 'Civic Engagement'],
    strategic_alignment: 'Medium — governance programs could align',
    notes: 'Initial contact made at Africa Philanthropy Forum 2025. Follow up with East Africa office.',
    tags: ['Foundation', 'Prospect', 'Governance'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2025-11-01T12:00:00Z',
    updated_at: '2026-01-08T10:00:00Z',
  },
  {
    id: '6',
    name: 'Equity Bank Foundation',
    category: 'Corporate',
    organization_type: 'Banking / Financial Services',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://www.equitybankfoundation.org',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Engagement Priority',
    program_areas: ['Youth Development', 'Entrepreneurship'],
    areas_of_interest: ['Education', 'Financial Literacy', 'Youth'],
    strategic_alignment: 'High — Wings to Fly and other scholarship programs',
    notes: 'Long-standing partnership. Annual co-programming budget allocated.',
    tags: ['Corporate', 'Education', 'Active Partner'],
    assigned_officer: 'James Otieno',
    created_at: '2023-06-15T09:00:00Z',
    updated_at: '2026-05-01T14:00:00Z',
  },
  {
    id: '7',
    name: 'British High Commission',
    category: 'Embassy',
    organization_type: 'Diplomatic Mission',
    country: 'United Kingdom',
    county: 'Nairobi',
    website: 'https://www.gov.uk/world/kenya',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Engagement Priority',
    program_areas: ['Climate Action', 'Digital Skills'],
    areas_of_interest: ['Governance', 'Climate', 'Education', 'Trade'],
    strategic_alignment: 'Medium — FCDO programs occasionally intersect with our work',
    notes: 'Chevening Scholarships coordination. FCDO-funded programs in arid counties.',
    tags: ['Embassy', 'UK Aid', 'Scholarships'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2024-04-10T11:00:00Z',
    updated_at: '2026-02-20T15:30:00Z',
  },
  {
    id: '8',
    name: 'UNICEF Kenya',
    category: 'NGO/Development Partner',
    organization_type: 'UN Agency',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://www.unicef.org/kenya',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Strategic Priority',
    program_areas: ['Youth Development', 'Health & Wellbeing', 'Women Empowerment'],
    areas_of_interest: ['Child Protection', 'Education', 'Health', 'Nutrition'],
    strategic_alignment: 'High — Child rights and education mandate',
    notes: 'Active collaboration on child protection programs in Turkana and Marsabit.',
    tags: ['UN', 'Child Protection', 'Active Partner'],
    assigned_officer: 'James Otieno',
    created_at: '2023-09-01T08:00:00Z',
    updated_at: '2026-05-10T09:45:00Z',
  },
  {
    id: '9',
    name: 'University of Nairobi',
    category: 'University/Research',
    organization_type: 'Public University',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://www.uonbi.ac.ke',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Engagement Priority',
    program_areas: ['Digital Skills', 'Entrepreneurship'],
    areas_of_interest: ['Research', 'Innovation', 'Youth', 'Technology'],
    strategic_alignment: 'Medium — research partnerships and student engagement',
    notes: 'MoU signed for research collaboration. Joint programs with the Faculty of Education.',
    tags: ['University', 'Research', 'MoU'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2026-04-05T13:15:00Z',
  },
  {
    id: '10',
    name: 'iHub Nairobi',
    category: 'Strategic Partner',
    organization_type: 'Innovation Hub',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://www.ihub.co.ke',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'Growth Opportunity',
    program_areas: ['Digital Skills', 'Entrepreneurship', 'Youth Development'],
    areas_of_interest: ['Tech Innovation', 'Entrepreneurship', 'Youth'],
    strategic_alignment: 'High — innovation ecosystem partner',
    notes: 'Co-hosting tech bootcamps. Exploring joint accelerator program.',
    tags: ['Innovation', 'Tech', 'Active Partner'],
    assigned_officer: 'James Otieno',
    created_at: '2024-07-15T09:00:00Z',
    updated_at: '2026-05-25T12:00:00Z',
  },
  {
    id: '11',
    name: 'KCB Foundation',
    category: 'Corporate',
    organization_type: 'Banking / Financial Services',
    country: 'Kenya',
    county: 'Nairobi',
    website: 'https://ke.kcbgroup.com/foundation',
    linkedin: null,
    twitter: null,
    status: 'Prospect',
    partner_priority: 'General Partner',
    program_areas: ['Entrepreneurship'],
    areas_of_interest: ['Agriculture', 'SME Development', 'Education'],
    strategic_alignment: 'Medium — 2jiajiri youth skills program',
    notes: 'Meeting requested for Q3 2026 to explore partnership on agri-youth program.',
    tags: ['Corporate', 'Prospect', 'Agriculture'],
    assigned_officer: 'Sarah Kamau',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-04-20T11:00:00Z',
  },
  {
    id: '12',
    name: 'German Embassy Nairobi',
    category: 'Embassy',
    organization_type: 'Diplomatic Mission',
    country: 'Germany',
    county: 'Nairobi',
    website: 'https://nairobi.diplo.de',
    linkedin: null,
    twitter: null,
    status: 'Active',
    partner_priority: 'General Partner',
    program_areas: ['Climate Action'],
    areas_of_interest: ['Climate', 'Vocational Training', 'Governance'],
    strategic_alignment: 'Medium — GIZ programs in vocational training',
    notes: 'GIZ office separately. Embassy small grants fund for cultural and social programs.',
    tags: ['Embassy', 'GIZ', 'Vocational'],
    assigned_officer: 'James Otieno',
    created_at: '2024-08-01T09:00:00Z',
    updated_at: '2026-03-10T14:00:00Z',
  },
];

export const seedContacts: Contact[] = [
  { id: 'c1', stakeholder_id: '1', full_name: 'Alice Mwangi', position: 'Africa Programs Director', email: 'alice.mwangi@gatesfoundation.org', phone: '+1-206-709-3400', linkedin: null, preferred_contact: 'Email', is_primary: true, created_at: '2024-01-15T09:00:00Z' },
  { id: 'c2', stakeholder_id: '2', full_name: 'Dr. Samuel Njoroge', position: 'East Africa Regional Lead', email: 's.njoroge@mastercardfdn.org', phone: '+254-722-100200', linkedin: 'linkedin.com/in/samuelnjoroge', preferred_contact: 'Email', is_primary: true, created_at: '2024-02-10T10:00:00Z' },
  { id: 'c3', stakeholder_id: '3', full_name: 'Grace Wanjiku', position: 'CSR & Partnerships Manager', email: 'gwanjiku@safaricom.co.ke', phone: '+254-722-000100', linkedin: null, preferred_contact: 'Phone', is_primary: true, created_at: '2024-03-05T08:00:00Z' },
  { id: 'c4', stakeholder_id: '3', full_name: 'Tom Kariuki', position: 'Foundation Manager', email: 'tkariuki@safaricomfoundation.org', phone: '+254-733-000200', linkedin: null, preferred_contact: 'Email', is_primary: false, created_at: '2024-03-06T08:00:00Z' },
  { id: 'c5', stakeholder_id: '4', full_name: 'Rebecca Johnson', position: 'Program Officer – Grants', email: 'rjohnson@state.gov', phone: '+254-20-363-6000', linkedin: null, preferred_contact: 'Email', is_primary: true, created_at: '2024-01-20T07:30:00Z' },
  { id: 'c6', stakeholder_id: '6', full_name: 'Peter Kimani', position: 'Foundation Director', email: 'pkimani@equitybank.co.ke', phone: '+254-763-000300', linkedin: 'linkedin.com/in/peterkimani', preferred_contact: 'Email', is_primary: true, created_at: '2023-06-15T09:00:00Z' },
  { id: 'c7', stakeholder_id: '8', full_name: 'Dr. Anne Achieng', position: 'Chief of Education', email: 'aachieng@unicef.org', phone: '+254-20-762-2500', linkedin: null, preferred_contact: 'Email', is_primary: true, created_at: '2023-09-01T08:00:00Z' },
  { id: 'c8', stakeholder_id: '9', full_name: 'Prof. David Ouma', position: 'Dean, Faculty of Education', email: 'd.ouma@uonbi.ac.ke', phone: '+254-20-318-262', linkedin: null, preferred_contact: 'Email', is_primary: true, created_at: '2024-06-01T10:00:00Z' },
  { id: 'c9', stakeholder_id: '10', full_name: 'Cynthia Mwangi', position: 'CEO', email: 'cynthia@ihub.co.ke', phone: '+254-722-400500', linkedin: 'linkedin.com/in/cynthiamwangi', preferred_contact: 'LinkedIn', is_primary: true, created_at: '2024-07-15T09:00:00Z' },
];

export const seedEngagements: Engagement[] = [
  { id: 'e1', stakeholder_id: '1', engagement_type: 'Meeting', date: '2026-04-10', summary: 'Quarterly partnership review meeting at Gates Foundation Nairobi office. Discussed Q2 milestone reporting and upcoming RFP.', outcome: 'RFP submission scheduled for June 2026. Positive reception on Q1 results.', follow_up_required: true, follow_up_date: '2026-06-15', responsible_officer: 'Sarah Kamau', created_by: null, created_at: '2026-04-10T14:00:00Z' },
  { id: 'e2', stakeholder_id: '2', engagement_type: 'Email', date: '2026-05-01', summary: 'Sent program progress report for Scholars Program cohort 3. Included attendance data and testimonials.', outcome: 'Acknowledged receipt. Formal review meeting to be scheduled.', follow_up_required: true, follow_up_date: '2026-05-20', responsible_officer: 'James Otieno', created_by: null, created_at: '2026-05-01T10:00:00Z' },
  { id: 'e3', stakeholder_id: '3', engagement_type: 'Meeting', date: '2026-03-15', summary: 'Initial CSR partnership scoping meeting at Safaricom HQ. Explored digital literacy program co-design.', outcome: 'Follow-up proposal requested by April 30.', follow_up_required: true, follow_up_date: '2026-04-30', responsible_officer: 'Sarah Kamau', created_by: null, created_at: '2026-03-15T11:00:00Z' },
  { id: 'e4', stakeholder_id: '4', engagement_type: 'Proposal Submission', date: '2026-02-28', summary: 'Submitted proposal for US Embassy Small Grants Program. Budget: $50,000 for youth civic engagement program.', outcome: 'Under review by grants committee.', follow_up_required: true, follow_up_date: '2026-04-15', responsible_officer: 'James Otieno', created_by: null, created_at: '2026-02-28T15:30:00Z' },
  { id: 'e5', stakeholder_id: '8', engagement_type: 'Partnership Discussion', date: '2026-05-10', summary: 'Strategic planning session with UNICEF Education team on joint program for pastoralist communities in Turkana.', outcome: 'Joint program framework agreed. MoU to be drafted by June.', follow_up_required: true, follow_up_date: '2026-06-01', responsible_officer: 'James Otieno', created_by: null, created_at: '2026-05-10T09:00:00Z' },
  { id: 'e6', stakeholder_id: '6', engagement_type: 'Phone Call', date: '2026-05-20', summary: 'Called Peter to discuss annual co-programming budget. He confirmed KES 5M allocated for FY2026.', outcome: 'Budget confirmed. Planning meeting set for June 10.', follow_up_required: true, follow_up_date: '2026-06-10', responsible_officer: 'James Otieno', created_by: null, created_at: '2026-05-20T14:00:00Z' },
  { id: 'e7', stakeholder_id: '5', engagement_type: 'Event Attendance', date: '2025-11-15', summary: 'Met Ford Foundation representative at Africa Philanthropy Forum 2025, Cape Town.', outcome: 'Business cards exchanged. Agreed to reconnect in Q1 2026.', follow_up_required: true, follow_up_date: '2026-01-15', responsible_officer: 'Sarah Kamau', created_by: null, created_at: '2025-11-15T18:00:00Z' },
];

export const seedOpportunities: Opportunity[] = [
  { id: 'o1', stakeholder_id: '1', name: 'Gates Foundation Education RFP 2026', description: 'Annual RFP for education programs in East Africa. Focus on early childhood education and digital learning.', funding_amount: 500000, currency: 'USD', deadline: '2026-06-30', status: 'Applying', responsible_officer: 'Sarah Kamau', notes: 'Expression of Interest submitted in April. Full proposal in progress.', created_at: '2026-04-01T09:00:00Z', updated_at: '2026-05-01T10:00:00Z' },
  { id: 'o2', stakeholder_id: '4', name: 'US Embassy Small Grants 2026', description: 'Youth civic engagement program grant. Budget up to $50,000.', funding_amount: 50000, currency: 'USD', deadline: '2026-04-15', status: 'Under Review', responsible_officer: 'James Otieno', notes: 'Proposal submitted Feb 28. Awaiting committee decision.', created_at: '2026-02-01T10:00:00Z', updated_at: '2026-03-01T09:00:00Z' },
  { id: 'o3', stakeholder_id: '2', name: 'Mastercard Scholars Program Extension', description: 'Extension of existing Scholars partnership for 2027-2030 cohort.', funding_amount: 1200000, currency: 'USD', deadline: '2026-09-30', status: 'Researching', responsible_officer: 'James Otieno', notes: 'Early discussions. Renewal of current agreement.', created_at: '2026-03-15T09:00:00Z', updated_at: '2026-04-01T10:00:00Z' },
  { id: 'o4', stakeholder_id: '3', name: 'Safaricom Digital Literacy CSR Partnership', description: 'Co-designed digital literacy program targeting 5,000 youth across Nairobi slums.', funding_amount: 8000000, currency: 'KES', deadline: '2026-05-31', status: 'Submitted', responsible_officer: 'Sarah Kamau', notes: 'Full proposal submitted April 30 as requested.', created_at: '2026-03-15T11:00:00Z', updated_at: '2026-05-01T09:00:00Z' },
  { id: 'o5', stakeholder_id: '6', name: 'Equity Foundation Co-Programming FY2026', description: 'Annual co-programming partnership for education and youth development.', funding_amount: 5000000, currency: 'KES', deadline: '2026-07-31', status: 'Identified', responsible_officer: 'James Otieno', notes: 'Budget confirmed. Planning meeting June 10.', created_at: '2026-05-20T14:00:00Z', updated_at: '2026-05-20T14:00:00Z' },
  { id: 'o6', stakeholder_id: '7', name: 'FCDO Arid Lands Education Grant', description: 'FCDO-funded program targeting out-of-school children in ASAL regions.', funding_amount: 300000, currency: 'USD', deadline: '2026-08-15', status: 'Identified', responsible_officer: 'Sarah Kamau', notes: 'RFP not yet released. Monitoring FCDO website.', created_at: '2026-04-01T09:00:00Z', updated_at: '2026-04-01T09:00:00Z' },
  { id: 'o7', stakeholder_id: '5', name: 'Ford Foundation Governance Grant', description: 'Grant to support civic education and governance programs.', funding_amount: 250000, currency: 'USD', deadline: '2026-12-31', status: 'Researching', responsible_officer: 'Sarah Kamau', notes: 'Need to make contact with East Africa Office first.', created_at: '2026-01-10T10:00:00Z', updated_at: '2026-02-01T09:00:00Z' },
  { id: 'o8', stakeholder_id: '4', name: 'USAID Youth Empowerment Grant 2025', description: 'Youth empowerment program. Application submitted last year.', funding_amount: 120000, currency: 'USD', deadline: '2025-09-30', status: 'Approved', responsible_officer: 'James Otieno', notes: 'Approved! Implementation started Jan 2026.', created_at: '2025-06-01T09:00:00Z', updated_at: '2025-10-15T10:00:00Z' },
];

export const seedFollowUps: FollowUp[] = [
  { id: 'f1', stakeholder_id: '1', engagement_id: 'e1', opportunity_id: 'o1', title: 'Submit Gates Foundation RFP Proposal', notes: 'Full proposal due June 30. Sarah leading drafting.', due_date: '2026-06-25', completed: false, completed_at: null, status: 'In Progress', priority: 'High', responsible_officer: 'Sarah Kamau', assigned_to: 'Sarah Kamau', created_at: '2026-04-10T14:00:00Z' },
  { id: 'f2', stakeholder_id: '2', engagement_id: 'e2', opportunity_id: 'o3', title: 'Schedule Mastercard Scholars Review Meeting', notes: 'Reach out to Dr. Njoroge for availability in June.', due_date: '2026-06-10', completed: false, completed_at: null, status: 'Pending', priority: 'Medium', responsible_officer: 'James Otieno', assigned_to: 'James Otieno', created_at: '2026-05-01T10:00:00Z' },
  { id: 'f3', stakeholder_id: '6', engagement_id: 'e6', opportunity_id: 'o5', title: 'Equity Bank Planning Meeting', notes: 'June 10 planning meeting for FY2026 co-programming budget.', due_date: '2026-06-10', completed: false, completed_at: null, status: 'Pending', priority: 'Medium', responsible_officer: 'James Otieno', assigned_to: 'James Otieno', created_at: '2026-05-20T14:00:00Z' },
  { id: 'f4', stakeholder_id: '8', engagement_id: 'e5', opportunity_id: null, title: 'Draft UNICEF MoU', notes: 'Legal team to review and draft MoU for joint program in Turkana.', due_date: '2026-06-01', completed: false, completed_at: null, status: 'In Progress', priority: 'High', responsible_officer: 'James Otieno', assigned_to: 'James Otieno', created_at: '2026-05-10T09:00:00Z' },
  { id: 'f5', stakeholder_id: '3', engagement_id: 'e3', opportunity_id: 'o4', title: 'Follow up on Safaricom Proposal Status', notes: 'Check with Grace on review timeline for digital literacy proposal.', due_date: '2026-06-05', completed: false, completed_at: null, status: 'Pending', priority: 'Medium', responsible_officer: 'Sarah Kamau', assigned_to: 'Sarah Kamau', created_at: '2026-05-01T09:00:00Z' },
  { id: 'f6', stakeholder_id: '4', engagement_id: 'e4', opportunity_id: 'o2', title: 'Check US Embassy Grant Decision', notes: 'Decision expected mid-April. Follow up if not heard by June 9.', due_date: '2026-06-09', completed: false, completed_at: null, status: 'On Hold', priority: 'Low', responsible_officer: 'James Otieno', assigned_to: null, created_at: '2026-04-15T10:00:00Z' },
  { id: 'f7', stakeholder_id: '5', engagement_id: 'e7', opportunity_id: null, title: 'Contact Ford Foundation East Africa Office', notes: 'Email introduction to East Africa office Director.', due_date: '2026-02-15', completed: true, completed_at: '2026-02-14T11:00:00Z', status: 'Completed', priority: 'Medium', responsible_officer: 'Sarah Kamau', assigned_to: 'Sarah Kamau', created_at: '2026-01-10T10:00:00Z' },
];
